### ISSUE TITLE
Missing OSM data

### ISSUE THREAD

**Issue by misiman** [OSMNames/OSMNames#167] opened 2018-08-02 11:46 UTC
Hi,

It appears there is some data missing from OSM in your full planet data-set.

A couple of examples are:

https://www.openstreetmap.org/node/298135719
https://www.openstreetmap.org/node/244082533

Do you know why this is?

Thanks

**Comment by misiman** [comment] 2018-08-09 14:25
I've found more missing/erroneous data:

https://www.openstreetmap.org/node/1767164377
https://www.openstreetmap.org/node/27365302

In OSMNames, the above nodes have the same Wikidata and Wikipedia entries although are completely unrelated.

Also, OSMNames gives Great Britain a Place Rank of 17 which is lower than London (Place Rank of 16), although London is the capital of England which is part of Great Britain.

Are these errors created during processing or import?

Thanks

**Comment by sfkeller** [comment] 2018-08-13 20:18
The first issue about same Wikidata is definitely related to the original data. You see in the changeset comment that that Wikidata was auto-matched with an erroneous result: https://www.openstreetmap.org/node/1767164377

The second issue about rankings assigned to Great Britain (country) and London (county) also seems related to the data - and I think data and place ranks are correct, since a country has a higher ranking as a county.

**Comment by misiman** [comment] 2018-08-14 09:30
Hi Stefan,

Thanks for explaining the Wikidata error, I wasn't sure if OSMNames rectified issues like this during the data deduplication/cleansing rountine?

Please can you clarify how place_rank is calculated? The documentation states that "lower means more important", meaning that the following (ordered in terms of importance and size) should not be the case as Great Britain would have a lower Place Rank number than England and London:

1) Great Britain - Place Rank 17 - http://osmnames.org/#q=great%20britain
2) England - Place Rank 8 - http://osmnames.org/#q=england
3) London - Plance Rank 16 - http://osmnames.org/#q=london

Also, do you know why the following nodes are missing from OSMNames, especially when Zigong is a large city:

https://www.openstreetmap.org/node/298135719
https://www.openstreetmap.org/node/244082533

Best regards

**Comment by sfkeller** [comment] 2018-08-14 09:47
I'm sorry that we can't be as responsive as we wish to be. This project is currently "under-maintained" and we can only give ad-hoc support (volunteers are welcome).

**Comment by misiman** [comment] 2018-08-15 10:25
Hi Philipp, thanks for your reply.

Understandably, some of the problem OSMNames encounters with prreparing imports is due to the complex and sometimes inconsistent nature of OpenStreetMap data.

I can help resolve issues, but would need some direct help from the OSMNames team?

**Comment by philippks** [comment] 2018-08-15 12:38
You're very welcome to help.

Solving #150 would be a fantastic contribution. 

I would be happy to help you getting used to the code base. Feel free to reach me in the other issue or via mail: philippks@use.startmail.com

I'll close this issue, since it looks like a duplicate of #150

**Closed by philippks** 2018-08-15 12:38 UTC
Labels: question
