### ISSUE TITLE
api returns bounding boxes with longitudes > 180

### ISSUE THREAD

**Issue by tyrasd** [OSMNames/OSMNames#141] opened 2017-10-02 13:17 UTC
Some requests return data where the `boundingbox` field has longitudes greater than 180 (while the content of the `lon` field is fine). Here's an example: `https://search.osmnames.org/q/Brazil.js` returns

![selection_039](https://user-images.githubusercontent.com/1927298/31079007-843444c0-a784-11e7-94f3-8cf12e14e36b.png)

//edit: the geometry of these bounding boxes is sometimes even "incorrect", it seems:

![selection_041](https://user-images.githubusercontent.com/1927298/31079474-129de404-a786-11e7-95a4-f7cc8fbb398d.png)

(but in other cases, like `Falkland Islands` it seems fine apart from the 360° shift)

**Comment by philippks** [comment] 2017-10-09 12:58
Hi @tyrasd, thanks for reporting the issue.

Seems like a bug at this place:
https://github.com/OSMNames/OSMNames/blob/master/osmnames/export_osmnames/functions.sql#L133

the corresponding tests can be found here:
https://github.com/OSMNames/OSMNames/blob/master/tests/export_osmnames/test_get_bounding_box.py

I'll check it out as soon as I have time (contributions welcome :wink: )

**Comment by MartinMikita** [comment] 2017-10-12 10:04
Another example: http://search.osmnames.org/q/Pinecliff%20Lake.js

**Comment by klokan** [comment] 2017-10-12 18:17
This is quite critical! It breaks production applications.

We may need to make on more bug fix release...

**Comment by m-mohr** [comment] 2017-10-16 22:44
More examples: "Pacific, Washington", "United States of America", "Russian Federation", ...

Sounds related to https://github.com/OSMNames/OSMNames/issues/94 and https://postgis.net/docs/ST_Shift_Longitude.html is pretty suspicious...

**Comment by philippks** [comment] 2017-10-17 09:34
#143 should fix the bug. I'm doing a new export right now and create a new release when finished and if correct.

**Comment by philippks** [comment] 2017-10-26 12:48
@MartinMikita @klokan 
I created a new release 2.0.3 as draft and uploaded the newest export. Could you review the newest export and give feedback about the new bounding boxes? 

I checked Brazil and the Falkland Island which are correct now. Unfortunately did the code changes behave strange for the huge relations like "United States of America" and "Russian Federation" why I hard coded these bounding boxes... Unfortunately I don't have much time right now to investigate further on the issue.

**Comment by MartinMikita** [comment] 2017-10-27 08:38
@philippks hard-coded bounding box for USA and RF are not working:

```
  "results": [
    {
      "wikipedia": "en:United States",
      "rank": 73755504.0,
      "county": "",
      "street": "",
      "wikidata": "Q30",
      "country_code": "us",
      "osm_id": "148838",
      "housenumbers": "",
      "id": 3,
      "city": "",
      "display_name": "United States of America",
      "lon": -99.009064,
      "state": "",
      "boundingbox": [
        -179.993515,
        -14.760836,
        180.0,
        71.60482
      ],
      "type": "administrative",
      "importance": 0.944692,
      "lat": 36.818432,
      "class": "boundary",
      "name": "United States of America",
      "country": "United States of America",
      "name_suffix": "",
      "osm_type": "relation",
      "place_rank": 4.0,
```

For Russian federation it is same bbox, -180 to 180.
Could you, please, check this ASAP?

**Comment by philippks** [comment] 2017-10-27 08:55
sorry @MartinMikita the export did not include the [latest commit](https://github.com/OSMNames/OSMNames/pull/143/commits/2eb6bfaf0738df2dd8e9ee4110f471b54421aae8) (which included the hardcoded bbox)... After pulling the commit, the bbox for us and rf are correct.

I suggest to manually change these values in the exported files. Could you do that? I would do it myself, but my internet connection is terrible slow right now... The corresponding values can be found [here](https://github.com/OSMNames/OSMNames/pull/143/commits/2eb6bfaf0738df2dd8e9ee4110f471b54421aae8). 

Sorry for the inconveniences.

btw, before publishing the release 2.0.3, the PR #143 must be merged first.

**Comment by m-mohr** [comment] 2017-11-13 22:16
Any news on this?

**Comment by philippks** [comment] 2017-11-14 06:19
yes, i uploaded yesterday the new export with the correct bbox for US and RF. Could you've a look @MartinMikita ?

**Comment by m-mohr** [comment] 2017-11-14 17:04
Is it possible for me to download it somewhere, @philippks? I'd like to check it against my data set as I am using it for a research paper. I have a list of 84 entries ([invalid-bboxes-osmnames.txt](https://github.com/OSMNames/OSMNames/files/1471782/invalid-bboxes-osmnames.txt)) that have invalid bboxes according to my tests and are affecting my research results.

**Comment by philippks** [comment] 2017-11-14 17:12
hey @m-mohr, I uploaded it as pre-release v2.0.3. You should see it on the[ releases page](https://github.com/OSMNames/OSMNames/releases).

I'm happy for any feedback.

**Comment by m-mohr** [comment] 2017-11-14 17:15
Oh, I had not checked the releases since some days, thanks @philippks. I'll rebuild my Lucene Index, run the tests and report the results probably tomorrow.

**Comment by m-mohr** [comment] 2017-11-14 18:58
Oh, I had not checked the releases since some days, thanks @philippks.

The only invalid bounding box reported is the South Pole. All other bounding boxes previously reported are valid (being between -180/180 and -90/90; I have not checked all their actual locations except Brazil and the US). Thanks for the fix.

**Comment by philippks** [comment] 2017-11-20 19:43
thanks for your feedback @m-mohr 
I merged the PR and released v2.0.3

I'll create a issue for the South Pole

**Comment by klokan** [comment] 2017-11-21 12:45
I would like to be sure the countries which are crossing dateline (such as New Zealand) remains to return from the API a bounding box larger than 180 - because this is really correct.

Could you please confirm @philippks - this is the case with the latest release?

http://osmnames.org/#q=new%20zealand
https://search.osmnames.org/q/new%20zealand.js

returns with last deployed release the bounds:
```
boundingbox: [
165.553375,
-52.821369,
184.458572,
-29.030331
],
```

The same bounds should be on v2.0.3 - to avoid regression of New Zealand query defined in #57

**Comment by klokan** [comment] 2017-11-21 12:55
Hmm, I see that Google Maps Geocoding APIs returns 
```
  "results" : [
      {
         "address_components" : [
            {
               "long_name" : "New Zealand",
               "short_name" : "NZ",
               "types" : [ "country", "political" ]
            }
         ],
         "formatted_address" : "New Zealand",
         "geometry" : {
            "bounds" : {
               "northeast" : {
                  "lat" : -28.8773225,
                  "lng" : -175.1235077
               },
               "southwest" : {
                  "lat" : -52.7224663,
                  "lng" : 165.7437641
               }
            },
            "location" : {
               "lat" : -40.900557,
               "lng" : 174.885971
            },
            "location_type" : "APPROXIMATE",
            "viewport" : {
               "northeast" : {
                  "lat" : -28.8773225,
                  "lng" : -175.1235077
               },
               "southwest" : {
                  "lat" : -52.7224663,
                  "lng" : 165.7437641
               }
            }
         },
         "place_id" : "ChIJh5Z3Fw4gLG0RM0dqdeIY1rE",
         "types" : [ "country", "political" ]
      }
   ],
   "status" : "OK"
}
 )
```

So the JavaScript is doing the dateline wrap probably...

We have to test our JavaScript clients on the "New Zealand" query - for example at https://osmnames.org/ and http://boundingbox.klokantech.com/ and elsewhere - if behaviour of zooming to the bounds crossing dateline is correct after we upgrade to OSMNames v2.0.3 data on our server @MartinMikita @petrsloup

**Comment by m-mohr** [comment] 2017-11-21 12:57
@klokan At the moment it returns [-179.0591531,-52.821369,179.3643594,-29.030331] which - unfortunately - is wrong at least for the longitude values.

**Comment by klokan** [comment] 2017-11-21 13:35
@philippks - could you please comment on your plans for solving this issue?

With bounding box [-179.0591531,-52.821369,179.3643594,-29.030331] it is not possible to recognize these are bounds crossing the dateline - instead, this is a polygon covering the whole world, which is wrong...

**Comment by philippks** [comment] 2017-11-21 18:37
hey @klokan, @m-mohr 
i actually updated 2.0.3 before the final release, so the current bbox for New Zealand is:
```
  "boundingbox": [
    165.553375,
    -52.821369,
    -175.541428,
    -29.030331
  ],
```

sorry for the silent change, but  the release @m-mohr downloaded was a pre-release.

The current bboxes are like on http://boundingbox.klokantech.com/. All in range [-180, 180]. This does not work well with osmnames-sphinxsearch right now (at least locally on my machine). But this may need changes of the rendering instead of the data? What do you think @klokan?

**Comment by m-mohr** [comment] 2017-11-21 19:31
Oh, thanks for the hint, @philippks. I just tried to download the new 2.0.3 release file, but they are only around 50MB in size. I think there went something wrong?!

**Comment by philippks** [comment] 2017-11-21 19:49
@m-mohr strange, it was stilled marked as draft. I published it again. Does it work now? Thanks for the feedback.

**Comment by philippks** [comment] 2017-11-22 15:45
thanks for the hint @m-mohr. I'm not sure about the "file size drop". Could be the smaller values to describe bounding boxes. Or maybe just changes in the OpenStreetMap data... I don't think we have to worry about it...

**Comment by klokan** [comment] 2017-11-23 14:11
OK. Thanks!

We will test and deploy the latest data if there is no problem anymore.

**Closed by klokan** 2017-11-23 14:11 UTC
Labels: bug, URGENT

**Comment by klokan** [comment] 2017-11-23 14:13
Download link updated: https://github.com/OSMNames/www.osmnames.org/commit/5a0396a3c7d09b4eb06586a1de299efb4ea85c95
