### ISSUE TITLE
Washington D.C. cannot be found

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#150] opened 2017-12-01 16:40 UTC
In the latest release seems to be also a problem with the ranking of "Washington District of Columbia".

It is ranked extremely low.

**Comment by philippks** [comment] 2017-12-05 11:16
The problem is, that OSMNames only exports [the relation](http://www.openstreetmap.org/relation/5396194) but not [the node](http://www.openstreetmap.org/node/158368533). The node is not exported because it is linked to the relation as `admin_center` (this is done [here](https://github.com/OSMNames/OSMNames/blob/master/osmnames/prepare_data/determine_linked_places.sql)).

To improve the data, the linked nodes should be considered when:
* collecting the names of the relation
* defining the importance of the relation
* maybe more?

Until now, linked nodes are simply skipped when exporting.

**Comment by misiman** [comment] 2018-08-17 18:43
Hi Philipp,

To help me understand the problem, would it be possible (presumably during import) to either perform one or both (for confirmation) of the below:

- On Relations: Check for "Place" nodes that are "Members" of a relation which contain the same "International/en" name as the relation
- On Nodes: Check "Part of" for "Relations" which contain the same "International/en" name as the node

And if this produces a match, then import both the relation and the node?

This logic seems to work for Washington DC and Zigong:

https://www.openstreetmap.org/relation/5396194
https://www.openstreetmap.org/node/158368533
https://www.openstreetmap.org/relation/2791218
https://www.openstreetmap.org/node/244082533

Thanks

**Comment by philippks** [comment] 2018-08-18 13:35
Hey @misiman 

To clarify, this is the current process:
1. both, the nodes and the relations are imported (nodes into the table osm_point and relations into the table osm_polygon)
2. when preparing the data, the admin_center nodes are linked to the relations ([here](https://github.com/OSMNames/OSMNames/blob/master/osmnames/prepare_data/determine_linked_places.sql))
3. when exporting the data, linked places are not exported at all ([here](https://github.com/OSMNames/OSMNames/blob/master/osmnames/export_osmnames/create_points_view.sql#L32))

My idea was to extend the information of the relations (osm_polygon) by the linked admin_centers. For example, when setting the names of the elements, a function could be added which adds the name of the admin_centers to the relation. This would take place [here](https://github.com/OSMNames/OSMNames/blob/master/osmnames/prepare_data/set_names.py), function e.g. extend_relation_names_by_admin_centers. But this process wouldn't make sense for a admin_center of a country, therefore it would be necessary to handle this (maybe by admin_level?)

The same would take place for the importance (https://github.com/OSMNames/OSMNames/blob/master/osmnames/export_osmnames/functions.sql#L85).

To be clear, this is just a proposal... But with your approach (exporting both, nodes and relations) I see the problem that it would result in a polygon and a node with the same name but different attributes, which would result in a not-so-nice usability for the users of the search.

Was I able to help you with that?

**Comment by misiman** [comment] 2018-08-20 19:09
Hi Philipp,

Thanks for the clarification - some thoughts:

"But this process wouldn't make sense for a admin_center of a country, therefore it would be necessary to handle this (maybe by admin_level?)" - Presumably this could be handled by only setting linked admin_centres where the place is a city, town, village, hamlet, etc

"But with your approach (exporting both, nodes and relations) ... would result in a not-so-nice usability for the users of the search." - The search is configured to show the result type, i.e. "administrative" or "city" so the user can select the most appropriate - see three London(s) for example:

http://osmnames.org/#q=london

Also, this is probably the reason why North Holmwood is missing from the export as I detailed in issue 167:

https://www.openstreetmap.org/relation/2891760
https://www.openstreetmap.org/node/298135719

So, it would seem that fixing this problem will significantly improve the OSMNames dataset completeness, providing users the opportunity to select a specific place or a polygon depending on their gazetteer purpose and georeferencing needs.

Your suggestion to "extend_relation_names_by_admin_centers" would appear to be most in keeping with the current codebase - I would help code this, but my Python/OSM skills are limited and I would be wary of introducing secondary errors or data inconsistencies by "trying".

I sincerely hope this change can move forward because, if so, OSMNames (combined with Sphinx/Elastic) would make one of the neatest, most accurate and fastest implementations of open source geodata that could power most common usage scenarios.

Thanks

**Comment by dragonbane0** [comment] 2018-10-11 01:29
@philippks Wouldn't it be reasonable in determine_linked_places.sql to simply update the required osm_polygon entries with the data from the linked osm_point nodes after the linking process is done? With that I mean copy over the wikipedia and wikidata tag as well as create a DISTINCT array of alternative_names from both. That should ensure the relations have all the alt names as well as the wikipedia info so that later get_place_importance calculates the right value for it. Am I missing something?

If not I will implement this

**Comment by philippks** [comment] 2018-10-11 14:57
> @philippks Wouldn't it be reasonable in determine_linked_places.sql to simply update the required osm_polygon entries with the data from the linked osm_point nodes after the linking process is done? With that I mean copy over the wikipedia and wikidata tag as well as create a DISTINCT array of alternative_names from both. That should ensure the relations have all the alt names as well as the wikipedia info so that later get_place_importance calculates the right value for it. Am I missing something?
> 
> If not I will implement this

sounds like an acceptable solution :+1:

only thing: i wouldn't put it into `determine_linked_places` but e.g. make a new function in the set_names.py file (maybe set_names_from_linked_places). For setting the wikipedia tags from the linked places i would add a new function (or even file). 

I'm happy to review your PR!

**Comment by philippks** [comment] 2019-05-01 15:39
with release v2.1 the attributes of the following nodes will be merged into their linked relation:

* label nodes
* political nodes (Washington D.C.)
* admin_center nodes where the node has either the same name, wikipedia- or wikidata-ref as the relation

admin_center nodes which can't be linked to any relation are exported as points to the OSMNames output.

**Comment by philippks** [comment] 2019-05-10 15:53
just saw that I accidentally uploaded the wrong version to the pre-release v2.1, where the node "Washington D.C." is not correctly merged into the relation. With the next export, this works correctly.

**Comment by philippks** [comment] 2019-05-15 08:00
fixed with [release v.2.1](https://github.com/OSMNames/OSMNames/releases/tag/v2.1.0)

**Closed by philippks** 2019-05-15 08:00 UTC
Labels: bug
