### ISSUE TITLE
Greece & Athens low ranked (wikipedia redirects)

### ISSUE THREAD

**Issue by m-mohr** [OSMNames/OSMNames#148] opened 2017-11-30 18:01 UTC
I just had a look at osmnames.org (and also at my custom Lucene index) and both can't find the country "Greece".

Also "Athens" returns places in the US, but not the one you would think of in the first place. When I insert "athens gr" it finds at least the "Municipality of Athens". 

What happens there? How can this be improved?

**Comment by MartinMikita** [comment] 2017-11-30 18:18
The problem is, that [Greece](http://www.openstreetmap.org/relation/192307) country relation has very small importance, which is used for sorting the entries in OSMNames.

```
{
  "wikipedia": "el:Ελλάδα",
  "rank": 1612251.125,
  "county": "",
  "street": "",
  "wikidata": "Q41",
  "country_code": "gr",
  "osm_id": "192307",
  "housenumbers": "",
  "id": 22541203,
  "city": "",
  "display_name": "Greece",
  "lon": 23.212204,
  "state": "",
  "boundingbox": [
    19.247787,
    34.700611,
    29.729698,
    41.748886
  ],
  "type": "administrative",
  **"importance": 0.093055,**
  "lat": 38.25687,
  "class": "boundary",
  "name": "Greece",
  "country": "Greece",
  "name_suffix": "",
  "osm_type": "relation",
  "place_rank": 4,
  "alternative_names": "ግሪክ,그리스,ޔޫނާން,ギリシャ,ଗ୍ରୀସ,ประเทศกรีซ,A' Ghrèig,An Ghréig,Buyonaani,Gelesi,Girees,Giriig,Görögország,Graecia,Grækenland,Grækerit Nunaat,Graikija,Grčija,Grčka,Grèce,Grecia,Grécia,Grècia,Grecja,Greċja,Grécko,Grèghia,Greika,Grekia,Grekland,Grekujo,Greqia,Gres,Grès,Gresi,Gresiýa,Gresya,Grétsiye,Grezia,Griechenland,Griekeland,Griekenland,Grieķija,Griicheland,Gríìsì,Grikän,Grikelân,Grikkaland,Grikkland,Grisy,Grisya,Grit,Gwíík Dineʼé Bikéyah,Gwlad Groeg,Gyresia,Hellas,Hy Lạp,IGreki,IGrikhi,Kirihi,Kreeka,Kreikka,Kuliti,Ngiriki,Pow Grek,Řecko,Ubugereki,Ugiriki,Yewnanistan,Yn Ghreag,Yunani,Yunanistan,Yunanıstan,Yunoniston,اليونان,یونان,يونان,גריכנלאנד,יוון,Ελλάδα,Ελληνική Δημοκρατία,Барзентәыла,Грек,Грекия,Грекъ,Греци,Греция,Греція,Грција,Грчка,Грьци,Грэцыя,Гърция,Эллада,Юнон,ཀེ་རི་སི།,གྲྀས,Հունաստան,საბერძნეთი,ग्रीस,यवनदेशः,यूनान,ગ્રીસ,గ్రీస్,ਯੂਨਾਨ,ಗ್ರೀಸ್,கிரேக்க நாடு,ഗ്രീസ്,গ্রিস,ဂရိနိုင်ငံ,ග්‍රීසිය,希腊"
}
```

For example, place [Greece in USA](http://www.openstreetmap.org/node/158636492) has higher importance:

```
{
  "wikipedia": "",
  "rank": 8103769,
  "county": "Greece Town",
  "street": "",
  "wikidata": "Q2610369",
  "country_code": "us",
  "osm_id": "158636492",
  "housenumbers": "",
  "id": 1025780,
  "city": "Greece Town",
  "display_name": "Greece, Greece Town, Monroe County, New York, United States of America",
  "lon": -77.693062,
  "state": "New York",
  "boundingbox": [
    -77.693062,
    43.209785,
    -77.693062,
    43.209785
  ],
  "type": "town",
  **"importance": 0.3,**
  "lat": 43.209785,
  "class": "place",
  "name": "Greece",
  "country": "United States of America",
  "name_suffix": "Greece Town, New York, US",
  "osm_type": "node",
  "place_rank": 18,
  "alternative_names": ""
}
```

**Comment by MartinMikita** [comment] 2017-11-30 18:19
@philippks Can you find out, why the importance of Greece country is so low?

**Comment by philippks** [comment] 2017-12-01 07:59
thanks for the feedback @m-mohr 

The problem is, that OSMNames takes the importance from Wikipedia, if the record has a link to it (determined with the `wikipedia` attribute). Unfortunately does the record for Greece point to [this Wikipedia article ](https://en.wikipedia.org/w/index.php?title=%CE%95%CE%BB%CE%BB%CE%AC%CE%B4%CE%B1&redirect=no). However, the importance of this article is very low, since it is only a redirect...

Btw. if there is no link to an Wikipedia article, the importance is calculated with this formular: `0.75 - place_rank / 40` (which would be 0.65 for Greece).

An obvious and easy solution for this problem would be to take the greatest of:
* importance from Wikipedia
* calculated importance

A cleaner solution would be to follow the redirection of the Wikipedia article. But this information is not provided in the Wikipedia dump OSMNames is using.

The same problem applies to `Athen` where the importance is 0 in the Wikipedia dump.

**Comment by philippks** [comment] 2017-12-01 09:16
the problem is see with just taking the greater of the two values is, that we would lose a fine granularity in the importance range . Half of the records with an link to Wikipedia have a lower importance from Wikipedia, then with the formula we use to calculate the importance (to be precise: 251664 of 498988).

Maybe we should take the greater value of both if the difference is large? (e.g. difference >= 0.35 results in 4462 of 498988 records). This would cover both examples, Athen and Greece.

**Comment by klokan** [comment] 2017-12-05 15:04
We really need to interpret the links in Wikipedia - and take the importance from the final article - not from the redirect page...

Related to the proper processing of Wikipedia / Wikidata - and imports as in OpenMapTiles #58

**Comment by philippks** [comment] 2019-05-15 08:00
fixed with [release v.2.1](https://github.com/OSMNames/OSMNames/releases/tag/v2.1.0)

**Closed by philippks** 2019-05-15 08:00 UTC
Labels: bug
